//
//  BookData.swift
//  book catalog
//
//  Created by TEMP on 4/19/20.
//  Copyright © 2020 aldovernando. All rights reserved.
//

import Foundation

class BookData {
    
    let bookDict: [ Int: Book ] =
        [
        0: Book(title: "The Secret Diary of Adrian Mole Aged 13 3/4 : Adrian Mole Book 1", released: "19 Jan 2012", author: "Sue Townsend", cover_image: "book1", synopsis: "I felt rotten today. It's my mother's fault for singing 'My Way' at two o'clock in the morning at the top of the stairs. Just my luck to have a mother like her. There is a chance my parents could be alcoholics. Next year I could be in a children's home.\n\nMeet Adrian Mole, a hapless teenager providing an unabashed, pimples-and-all glimpse into adolescent life. Writing candidly about his parents' marital troubles, the dog, his life as a tortured poet and 'misunderstood intellectual', Adrian's painfully honest diary is still hilarious and compelling reading thirty years after it first appeared."),
    
         1: Book(title: "The Golden Notebook", released: "17 Jan 2013", author: "Doris Lessing", cover_image: "book2", synopsis: "In 1950s London, novelist Anna Wulf struggles with writer's block. Divorced with a young child, and fearful of going mad, Anna records her experiences in four coloured notebooks: black for her writing life, red for political views, yellow for emotions, blue for everyday events. But it is a fifth notebook - the golden notebook - that finally pulls these wayward strands of her life together."),
         
         2: Book(title: "Jane Eyre", released: "01 Aug 1997", author: "Charlotte Bronte", cover_image: "book3", synopsis: "Jane Eyre ranks as one of the greatest and most perennially popular works of English fiction. Although the poor but plucky heroine is outwardly of plain appearance, she possesses an indomitable spirit, a sharp wit and great courage.\n\nShe is forced to battle against the exigencies of a cruel guardian, a harsh employer and a rigid social order. All of which circumscribe her life and position when she becomes governess to the daughter of the mysterious, sardonic and attractive Mr Rochester."),
         
         3: Book(title: "The Goldfinch", released: "19 Oct 2015", author: "Donna Tartt", cover_image: "book4", synopsis: "Aged thirteen, Theo Decker, son of a devoted mother and a reckless, largely absent father, survives an accident that otherwise tears his life apart. Alone and rudderless in New York, he is taken in by the family of a wealthy friend. He is tormented by an unbearable longing for his mother, and down the years clings to the thing that most reminds him of her: a small, strangely captivating painting that ultimately draws him into the criminal underworld. As he grows up, Theo learns to glide between the drawing rooms of the rich and the dusty antiques store where he works. He is alienated and in love - and his talisman, the painting, places him at the centre of a narrowing, ever more dangerous circle."),
         
         4: Book(title: "The Name Of The Rose", released: "01 Jul 2011", author: "Umberto Eco", cover_image: "book5", synopsis: "The year is 1327. Franciscans in a wealthy Italian abbey are suspected of heresy, and Brother William of Baskerville arrives to investigate. When his delicate mission is suddenly overshadowed by seven bizarre deaths, Brother William turns detective.\n\nWilliam collects evidence, deciphers secret symbols and coded manuscripts, and digs into the eerie labyrinth of the abbey where extraordinary things are happening under the cover of night. A spectacular popular and critical success, The Name of the Rose is not only a narrative of a murder investigation but an astonishing chronicle of the Middle Ages."),
         
         5: Book(title: "The Kite Runner", released: "11 Dec 2018", author: "Khaled Hosseini", cover_image: "book6", synopsis: "Afghanistan, 1975: Twelve-year-old Amir is desperate to win the local kite-fighting tournament and his loyal friend Hassan promises to help him. But neither of the boys can foresee what will happen to Hassan that afternoon, an event that is to shatter their lives. After the Russians invade and the family is forced to flee to America, Amir realises that one day he must return to Afghanistan under Taliban rule to find the one thing that his new world cannot grant him: redemption."),
         
         6: Book(title: "The House of the Spirits", released: "08 Feb 2017", author: "Isabel Allende", cover_image: "book7", synopsis: "As a girl, Clara del Valle can read fortunes, make objects move as if they had lives of their own, and predict the future. Following the mysterious death of her sister, Rosa the Beautiful, Clara is mute for nine years. When she breaks her silence, it is to announce that she will be married soon to the stern and volatile landowner Esteban Trueba.\n\nSet in an unnamed Latin American country over three generations, The House of the Spirits is a magnificent epic of a proud and passionate family, secret loves and violent revolution."),
         
         7: Book(title: "Call Me By Your Name", released: "03 Apr 2018", author: "Andre Aciman", cover_image: "book8", synopsis: "Andre Aciman's Call Me by Your Name is the story of a sudden and powerful romance that blossoms between an adolescent boy and a summer guest at his parents' cliffside mansion on the Italian Riviera. Each is unprepared for the consequences of their attraction, when, during the restless summer weeks, unrelenting currents of obsession, fascination, and desire intensify their passion and test the charged ground between them. Recklessly, the two verge toward the one thing both fear they may never truly find again: total intimacy. It is an instant classic and one of the great love stories of our time."),
         
         8: Book(title: "Memoirs of a Geisha", released: "20 Jun 2011", author: "Arthur Golden", cover_image: "book9", synopsis: "A young peasant girl is sold as servant and apprentice to a renowned geisha house. She tells her story many years later from the Waldorf Astoria in New York. Her memoirs conjure up the perfection and the ugliness of life behind rice-paper screens, where young girls learn the arts of geisha - dancing and singing, how to wind the kimono, how to walk and pour tea, and how to beguile the land's most powerful men."),
         
         9: Book(title: "Peace Like a River", released: "04 Oct 2018", author: "Leif Enger", cover_image: "book10", synopsis: "When Israel Finch and Tommy Basca, the town bullies, break into the home of school caretaker Jeremiah Land, wielding a baseball bat and looking for trouble, they find more of it than even they expected. For seventeen-year-old Davey is sitting up in bed waiting for them with a Winchester rifle. His younger brother Reuben has seen their father perform miracles, but Jeremiah now seems as powerless to prevent Davey from being arrested for manslaughter, as he has always been to ease Reuben's daily spungy struggle to breathe. Nor does brave and brilliant nine-year-old Swede, obsessed as she is with the legends of the wild west, have the strength to spring Davey from jail. Yet Davey does manage to break out. He steals a horse, and disappears. His family feels his absence so sorely, the three of them just pile into their old Plymouth, towing a brand new 1963 Airstream trailer, and set out on a quest to find him. And they follow the outlaw west, right into the cold, wild and empty Dakota Badlands."),
         
         10: Book(title: "A Little Life : Shortlisted for the Man Booker Prize 2015", released: "10 Mar 2016", author: "Hanya Yanagihara", cover_image: "book11", synopsis: "When four graduates from a small Massachusetts college move to New York to make their way, they're broke, adrift, and buoyed only by their friendship and ambition. There is kind, handsome Willem, an aspiring actor; JB, a quick-witted, sometimes cruel Brooklyn-born painter seeking entry to the art world; Malcolm, a frustrated architect at a prominent firm; and withdrawn, brilliant, enigmatic Jude, who serves as their centre of gravity. Over the decades, their relationships deepen and darken, tinged by addiction, success, and pride. Yet their greatest challenge, each comes to realize, is Jude himself, by midlife a terrifyingly talented litigator yet an increasingly broken man, his mind and body scarred by an unspeakable childhood, and haunted by what he fears is a degree of trauma that he'll not only be unable to overcome - but that will define his life forever."),
         
         11: Book(title: "Mosquitoland", released: "10 Sep 2015", author: "David Arnold", cover_image: "book12", synopsis: "When her parents unexpectedly divorce, Mim Malone is dragged from her beloved home in Ohio to the 'wastelands' of Mississippi, where she lives in a haze of medication with her dad and new (almost certainly evil) stepmom.\n\nBut when Mim learns her real mother is ill back home, she escapes her new life and embarks on a rescue mission aboard a Greyhound bus, meeting an assortment of quirky characters along the way. And when her thousand-mile journey takes a few turns she could never see coming, Mim must confront her own demons, redefining her notions of love, loyalty, and what it means to be sane."),
         
         12: Book(title: "The Time of My Life", released: "10 May 2012", author: "Cecelia Ahern", cover_image: "book13", synopsis: "Lucy Silchester is. She's busied herself with other stuff: friends' lives, work issues, her deteriorating car, that kind of thing. But she's stuck in a rut - and deluding everyone. Only Lucy knows the real truth.\n\nTime for a wake-up call - a meeting with life. And life turns out to be a kindly, rather run-down man in an old suit, who is determined to bring about change - and won't let Lucy off the hook."),
         
         13: Book(title: "Remembering Shanghai : A Memoir of Socialites, Scholars and Scoundrels", released: "01 May 2018", author: "Claire Chao", cover_image: "book14", synopsis: "When Mao comes to power, eighteen-year-old Isabel journeys to Hong Kong, not realizing that she will make it her home--and that she will never see her father again. Meanwhile, the family she has left behind struggles to survive, only to have their world shattered by the Cultural Revolution. Isabel returns to Shanghai fifty years later with her daughter, Claire, to confront their family's past--one they discover is filled with love and betrayal, kidnappers and concubines, glittering pleasure palaces and underworld crime bosses."),
         
         14: Book(title: "Divergent", released: "05 Oct 2012", author: "Veronica Roth", cover_image: "book15", synopsis: "For sixteen-year-old Tris, the world changes in a heartbeat when she is forced to make a terrible choice. Turning her back on her family, Tris ventures out, alone, determined to find out where she truly belongs.\n\nShocked by the brutality of her new life, Tris can trust no one. And yet she is drawn to a boy who seems to both threaten and protect her. The hardest choices may yet lie ahead....")
         
        ]
    
}
